name: Build

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

env:
  dotnet_sdk_version: '5.0.x'
  postgis_version: 3
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      release: ${{ steps.check_release.outputs.release }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, windows-2019 ]
        pg_major: [ 13, 12, 11, 10 ]

    steps:
      - id: check_release
        name: Check whether to release
        shell: bash
        run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
              echo "::set-output name=release::true"
          fi



  release:
    needs: build

    runs-on: ubuntu-20.04

    if: github.event_name == 'push' && github.repository == 'roji/npgsql' && needs.build.outputs.release == 'true'

    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#
#      - name: NuGet Cache
#        uses: actions/cache@v2.1.5
#        with:
#          path: ~/.nuget/packages
#          key: ${{ runner.os }}-nuget-${{ hashFiles('**/Directory.Build.targets') }}
#          restore-keys: |
#            ${{ runner.os }}-nuget-
#
#      - name: Setup .NET Core SDK
#        uses: actions/setup-dotnet@v1
#        with:
#          dotnet-version: ${{ env.dotnet_sdk_version }}
#
#      - name: Pack
#        run: dotnet pack Npgsql.sln --configuration Release --output nupkgs -p:ContinuousIntegrationBuild=true
#        shell: bash
#
#      - name: Upload artifacts (nupkg)
#        uses: actions/upload-artifact@v2
#        with:
#          name: Release.nupkgs
#          path: nupkgs

      - name: Analyze tag
        shell: bash
        run: |
          echo "tag_name=${GITHUB_REF##*/}" >> $GITHUB_ENV
          if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+.*- ]]; then
            echo "prerelease=true" >> $GITHUB_ENV
          fi

      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
# TODO: Chop off leading v, and remove -* for previews (point to the 6.0.0 milestone from v6.0.0-preview1)          
#          body: The list of changes is available [here](https://github.com/npgsql/npgsql/issues?q=is%3Aissue+milestone%3A${{ env.tag_name }}).
          prerelease: ${{ env.PRERELEASE }}
          token: ${{ secrets.GITHUB_TOKEN }}


#      - name: Publish to nuget.org
#        run: dotnet nuget push "*.nupkg" --api-key ${{ secrets.NUGET_FEED_TOKEN }} #--source https://www.myget.org/F/npgsql/api/v3/index.json
#        working-directory: nupkgs
#        shell: bash
